author:
  email: gert.lombard@gmail.com
  name: Gert Lombard
  url: https://twitter.com/codeblast
baseurl: http://codeblast.com
github:
  repo: https://github.com/glombard/glombard.github.io
highlighter: pygments
pages:
  About: /about
  Archive: /archive
  Feed: /atom.xml
paginate: 5
permalink: pretty
relative_permalinks: true
sass:
  sass_dir: _sass
  style: :compressed
tagline: Android testing and random thoughts on software development.
title: Gert Lombard's Blog
url: http://codeblast.com
version: 1.0.1
