author:
  email: gert.lombard@gmail.com
  name: Gert Lombard
  url: https://twitter.com/codeblast
baseurl: ''
gems:
- jekyll-paginate
github:
  repo: https://github.com/glombard/glombard.github.io
highlighter: rouge
links:
  About: /about
  Archive: /archive
  Feed: /atom.xml
paginate: 5
permalink: pretty
relative_permalinks: false
sass:
  sass_dir: _sass
  style: :compressed
tagline: My passion is code quality, automated testing, software craftsmanship.
title: Gert Lombard's Blog
url: http://codeblast.com
version: 1.0.5
