author:
  email: gert.lombard@gmail.com
  name: Gert Lombard
  url: https://twitter.com/codeblast
baseurl: /
github:
  repo: https://github.com/glombard/glombard.github.io
paginate: 1
permalink: pretty
relative_permalinks: true
tagline: Android testing and random thoughts on software development.
title: Gert Lombard's Blog
url: http://codeblast.com
version: 1.0.0
